# Generated by Django 4.0.1 on 2022-01-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
