# Generated by Django 4.0.3 on 2022-03-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='national_id_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
