# Generated by Django 4.0.3 on 2022-03-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_id_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
