# Generated by Django 4.0.3 on 2022-03-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_blog_accepted_alter_profile_national_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='access',
        ),
    ]
