# Generated by Django 4.0.3 on 2022-03-22 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.profile'),
        ),
    ]
