# Generated by Django 4.0.3 on 2022-03-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_blog_admin_notes_blog_user_notes_alter_blog_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='اولین وبلاگ ساخته شده', max_length=256),
            preserve_default=False,
        ),
    ]
